const swaggerAutogen = require("swagger-autogen")();

const doc = {
	info: {
		version: "1.0.0",
		title: "App API",
		description:
			"Documentation automatically generated by the <b>swagger-autogen</b>.",
	},
	host: ["localhost:4000"],
	basePath: "/",
	schemes: ["http", "https"],
	consumes: ["application/json"],
	produces: ["application/json"],
	securityDefinitions: {
		// apiKeyAuth: {
		// 	type: "bearerKey",
		// 	in: "header", // can be "header", "query" or "cookie"
		// 	name: "Authentication", // name of the header, query parameter or cookie
		// },
	},
	definitions: {
		Sign: {
			email: "ibrahimsadiktamim@gmail.com",
			password: "12345678",
		},
	},
};

const outputFile = "./swagger.json";
const endpointsFiles = ["./app.js"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
	require("./index"); // Your project's root file
});
